### ISSUE TITLE
Ch1-4

### ISSUE THREAD

**Issue by tacryt-socryp** [joshuareagan/doc-drafts#1]
Hi there, I'm loving your tutorial so far.

I think there's some ambiguity around how the & limb expression is evaluated. From the tutorial, I'm unsure how the tree is being traversed to decide the 'order' of the elements. It doesn't seem to match an intuitive pattern.

For instance, I expected:
`&2:[1 [[2 3] 3]]`
to evaluate to: 2, but it actually evaluates to [2 3].
Further:
`&3:[1 [[2 3] 3]]`
nest fails, and I'm unsure why.

**Comment by joshuareagan** [comment]
Sorry for the delayed response--I missed this comment because somehow I'm not subscribed to my own repository.

`&n` resolves to the n-th noun of a 'list', not the n-th atom.  The first noun is the atom `1`, but the second noun is the cell `[2 3]`.  So that's the correct result for `&2`.  The answer isn't the cell `[[2 3] 3]` because `[1 [[2 3] 3]]` is the same cell as `[1 [2 3] 3]`, so as a 'list' the last `3` is the third noun.

`&3` nest-fails because the `&n` operator only works if there are at least `n+1` nouns in the 'list'.  But `[1 [[2 3] 3]]` only has three nouns, list-wise: `1`, `[2 3]`, and `3`.

Does this make sense?

This can be made clearer in the tutorial, so I'll make sure I circle back to that.

**Comment by joshuareagan** [comment]
To add one more thing...

What do I mean by list?  Here I'm speaking loosely of a non-null-terminated list.  The head is the first item of the list and the tail is the rest of the list.  The head of the rest of the list is the next item, and the tail of the rest is the rest of the list.  The head of the latter is the next item... and so on.

**Comment by tacryt-socryp** [comment]
Thank you for explaining!
